_wandb:
    value:
        cli_version: 0.19.2
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
                - 80
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
                - 80
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.8.20
            "5": 0.19.2
            "8":
                - 3
                - 5
                - 9
            "12": 0.19.2
            "13": windows-amd64
batch_size:
    value: 8
epochs:
    value: 150
learning_rate:
    value: 5e-06
optimizer:
    value: AdamW
scheduler:
    value: CosineAnnealingLR
